global: &global
  adapter: mysql2
  pool: 100
  timeout: 5000
  username: root
  password: hasankhan
  host: localhost
  socket: /Applications/MAMP/tmp/mysql/mysql.sock

development:
  <<: *global
  database: brandesh_dev
